# Generated by Django 4.1.7 on 2023-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0002_group_owner_alter_group_description_alter_ride_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
