# Generated by Django 4.1.7 on 2023-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0003_alter_userprofile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
