# Generated by Django 4.1.7 on 2023-05-05 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0006_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='name',
        ),
        migrations.AddField(
            model_name='ride',
            name='seat',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
